[theme]
primaryColor = "#DF5830"
backgroundColor = "#FAF8F5"
secondaryBackgroundColor = "#F2EDE6"
textColor = "#1C1917"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
